mqtt_client:
  ros__parameters:
    broker:
      host: localhost
      port: 1883
    bridge:
      ros2mqtt:
        topics:
          - ping
        ping:
          ros_topic: /ping/primitive
          mqtt_topic: pingpong/primitive
          primitive: true
      mqtt2ros:
        topics:
          - pong
        pong:
          mqtt_topic: pingpong/primitive
          ros_topic: /pong/primitive
          primitive: true
