mqtt_client:
  ros__parameters:
    broker:
      host: localhost
      port: 1883
    bridge:
      ros2mqtt:
        topics:
          - ping
        ping:
          ros_topic: /ping/ros
          mqtt_topic: pingpong/ros
      mqtt2ros:
        topics:
          - pong
        pong:
          mqtt_topic: pingpong/ros
          ros_topic: /pong/ros
