# YAML aliases for MQTT SSL version.
default: &default 0
tls_1_0: &tls_1_0 1
tls_1_1: &tls_1_1 2
tls_1_2: &tls_1_2 3

broker:
  host: iot-pr.oxin.nz
  port: 8883
  tls:
    enabled: true
    ca_certificate: /opt/oxin/certs/AmazonRootCA1.pem
client:
  id: oxx1
  # Whether or not to start a clean session with each reconnect.
  # If True, the server will forget all subscriptions with each reconnect.
  # Set False to request that the server resume an existing session or start
  # a new session that may be resumed after a connection loss.
  clean_session: false
  # The keep alive value, in seconds, to send in CONNECT packet.
  keep_alive_interval: 6.0
  tls:
    certificate: /opt/oxin/certs/57259bb1ea8ddc6e11cda45387e7e4f360bd76e668a7cfbfa4bdc7c34071a31f-certificate.pem.crt
    key: /opt/oxin/certs/57259bb1ea8ddc6e11cda45387e7e4f360bd76e668a7cfbfa4bdc7c34071a31f-private.pem.key
    # AWS uses TLS 1.2 to encrypt all communication.
    version: *tls_1_2
    verify: true
    # https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_alpn_protos.html
    alpn_protos:
      # MQTT over AWS IOT requires an ALPN protocol negotiation.
      # https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html
      - x-amzn-mqtt-ca
  buffer:
    enabled: true
bridge:
  ros2mqtt:
    - mqtt_topic: vehicle/oxx1/heartbeat
      ros_topic: /mqtt/heartbeat
      primitive: true
  mqtt2ros:
    - mqtt_topic: vehicle/oxx1/command
      ros_topic: /mqtt/command
      primitive: true
    - mqtt_topic: vehicle/oxx1/heartbeat
      ros_topic: /mqtt/heartbeat
      primitive: true
    - mqtt_topic: vehicle/oxx1/base
      ros_topic: /mqtt/basestation
      primitive: true
